name: Create PDF
on:
  push:
    tags:
    - 'v*'

jobs:
  create_pdf_job:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
      - run: |
          npm install
          node ./md2pdf.js
      - name: Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: |
            curriculum-vitae-jp.pdf
            curriculum-vitae-en.pdf
