name: Create PDF
on:
  push:
    tags:
    - 'v*'

jobs:
  create_pdf_job:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.9.1"
      - name: install japanese font
        run: sudo apt install fonts-sawarabi-gothic
      - run: |
          npm install
          node ./md2pdf.js
      - uses: actions/upload-artifact@v1
        with:
          name: jp-pdf
          path: ./jp/README.pdf
      - uses: actions/upload-artifact@v1
        with:
          name: en-pdf
          path: ./en/README.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./jp/curriculum-vitae.pdf
            ./en/curriculum-vitae.pdf
