name: Create PDF
on: push

jobs:
  create_pdf_job:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "8.16.0"
      - run: |
          npm install
          node ./md2pdf.js
      - uses: actions/upload-artifact@v1
        with:
          name: jp-pdf
          path: ./jp/README.pdf
      - uses: actions/upload-artifact@v1
        with:
          name: en-pdf
          path: ./en/README.pdf